### ISSUE TITLE
Opening a jp_proxy_widget in a separate JupyterLab window

### ISSUE THREAD

**Issue by psychemedia** [AaronWatters/jp_proxy_widget#12]
It would be really useful to be able to open a `jp_proxy_widget` in a new JupyterLab output window. This would provide a simple mechanism for then creating JupyterLab apps running in their own window as simple `jp_proxy_widget` wrapped Javascript applications.

Related issue: https://github.com/jupyterlab/jupyterlab/issues/3692

I had wondered in the past if [`jupyterlab-sidecar'](https://github.com/jupyter-widgets/jupyterlab-sidecar/) might offer an alternative route (or suggest some plumbing that would allow a widget to be opened directly in a new output window) but it appears to be a stale project?

**Comment by AaronWatters** [comment]
Yes, I think this would be nice for any complex widget.  Maybe suggest or ask about it with the ipywidgets implementors?
I actually was under the impression that this was possible already (but I haven't actually seen it).

**Comment by psychemedia** [comment]
Just revisiting JupyterLab again again (I can't really keep up with its version changes), and `jp_proxy_widget` seems not to work in any of the MyBinder environment's I've tried, raising a "model canlt be found" message if I try to load run even the code in simple hello-word demo notebook.

Just me or has JupyterLab updates broken things in JupyterLab context again?

**Comment by AaronWatters** [comment]
sorry.  This was my fault. I merged a pull request too quickly without checking all the test cases.

https://github.com/AaronWatters/jp_proxy_widget/commit/65159b870a62e01009e0fa14dc8bf8029e089168

That should fix the problem.  Please let me know if it doesn't or if you see other issues.  Thanks!

**Comment by psychemedia** [comment]
I just ran the repo in MyBinder and still get the issue?

![image](https://user-images.githubusercontent.com/82988/110517582-f24d4500-8102-11eb-9e9a-acf4aa0aeb3b.png)

**Comment by AaronWatters** [comment]
&^%$

I think I fixed it.

I had to bump a version number in package.json.

I wish they'd stop doing this....  it happens about once every 6 months....

**Comment by psychemedia** [comment]
Seems to work fine now from a Binderised version of your repo, but not from sidecar Binder? And sidecar which I did have working in some Binderised environment somewhere today is now not working...

I have wasted so much time going nowhere trying to do anything ever in JupyterLab ;-)

I am going to park trying to get my widgets working in JupyterLab for another 3 months again, I think! JupyterLab seems to continue to be a really brittle dependency hell environment. And the install JupyterLab rebuilds still take forever.... I hate it, hate it, hate it!;-)

**Comment by psychemedia** [comment]
I need to start revisiting this idea again (running a `jp_proxy_widget` js app in a "torn off" or separate window or sidecar widget. Do you have or know of any widgets that demo this working?

**Comment by psychemedia** [comment]
JUst as a placeholder, at some point in the past, just to note that `sidecar` and `jp_proxy_widget` did play nice for a period and you could display a `jp_proxy_widget` wrapped widget in a sidecar panel: https://blog.ouseful.info/2021/09/22/getting-nbev3devsim-running-in-jupyterlab/

I'm not sure what happened if you tried to open sidecar panels in separate notebooks in the same JupyyterLab view, each rendering a `jp_proxy_widget`? I guess there may have been an `id` conflict?
